### ISSUE TITLE
SignalR expects cookie header to be set

### ISSUE THREAD

**Issue by TheRealest** [dparlevliet/node.bittrex.api#11]
My code:
```
bittrex = require 'node.bittrex.api'

bittrex.options
  apikey: XXX
  apisecret: XXX
  inverse_callback_arguments : true
  verbose: true

bittrex.websockets.listen ->
  console.log arguments
  console.log 'listening'
```

I'm getting this error:
```
_http_outgoing.js:487
    throw new Error('"value" required in setHeader("' + name + '", value)');
    ^

Error: "value" required in setHeader("cookie", value)
  at validateHeader (_http_outgoing.js:487:11)
  at ClientRequest.setHeader (_http_outgoing.js:496:3)
  at new ClientRequest (_http_client.js:171:14)
  at Object.request (http.js:39:10)
  at Object.request (https.js:239:15)
  at Object.get (https.js:243:21)
  at negotiateProxies (/Users/realp/projects/belfort/node_modules/signalr-client/signalR.js:154:37)
  at getBindings (/Users/realp/projects/belfort/node_modules/signalr-client/signalR.js:161:5)
  at Object._client.getBinding (/Users/realp/projects/belfort/node_modules/signalr-client/signalR.js:756:9)
  at clientInterface.client.start (/Users/realp/projects/belfort/node_modules/signalr-client/signalR.js:440:17)
  at /Users/realp/projects/belfort/node_modules/node.bittrex.api/node.bittrex.api.js:166:18
  at giveResults (/Users/realp/projects/belfort/node_modules/cloudscraper/index.js:244:5)
  at Request._callback (/Users/realp/projects/belfort/node_modules/cloudscraper/index.js:109:7)
  at Request.self.callback (/Users/realp/projects/belfort/node_modules/request/request.js:188:22)
  at emitTwo (events.js:125:13)
  at Request.emit (events.js:213:7)
  at Request.<anonymous> (/Users/realp/projects/belfort/node_modules/request/request.js:1171:10)
  at emitOne (events.js:115:13)
  at Request.emit (events.js:210:7)
  at IncomingMessage.<anonymous> (/Users/realp/projects/belfort/node_modules/request/request.js:1091:12)
  at Object.onceWrapper (events.js:314:30)
  at emitNone (events.js:110:20)
  at IncomingMessage.emit (events.js:207:7)
  at endReadableNT (_stream_readable.js:1059:12)
  at _combinedTickCallback (internal/process/next_tick.js:138:11)
 ```

But if I change this line https://github.com/dparlevliet/node.bittrex.api/blob/master/node.bittrex.api.js#L153:
```
opts.headers = {
  cookie: response.request.headers["cookie"] || '', // protection against undefined value
  user_agent: response.request.headers["User-Agent"]
};
```
... it works.

So I must have gotten into a situation where Cloudscrape is not returning a cookie because I don't need it? It worked the first few times I ran it, then I just started getting this error, so I'm assuming I'm no longer hitting the Cloudflare challenge page, so I'm not getting the cookie, but SignalR doesn't seem to like headers to have undefined values. Probably should put the `|| ''` in there or conditionally set the headers individually in the first place.

**Comment by TheRealest** [comment]
PR with fix: https://github.com/dparlevliet/node.bittrex.api/pull/12
