### ISSUE TITLE
Error: "value" required in setHeader("cookie", value)

### ISSUE THREAD

**Issue by paveltaran** [dparlevliet/node.bittrex.api#13]
node bittrex.websockets.listen.example.js

Connecting ....
_http_outgoing.js:502
    throw new Error('"value" required in setHeader("' + name + '", value)');
    ^

Error: "value" required in setHeader("cookie", value)
    at validateHeader (_http_outgoing.js:502:11)
    at ClientRequest.setHeader (_http_outgoing.js:511:3)
    at new ClientRequest (_http_client.js:171:14)
    at Object.request (http.js:39:10)
    at Object.request (https.js:233:15)
    at Object.get (https.js:237:21)
    at negotiateProxies (/private/tmp/node.bittrex.api/node_modules/signalr-client/signalR.js:154:37)
    at getBindings (/private/tmp/node.bittrex.api/node_modules/signalr-client/signalR.js:161:5)
    at Object._client.getBinding (/private/tmp/node.bittrex.api/node_modules/signalr-client/signalR.js:756:9)
    at clientInterface.client.start (/private/tmp/node.bittrex.api/node_modules/signalr-client/signalR.js:440:1

**Comment by dparlevliet** [comment]
I believe this has been fixed earlier today - please make sure your package/repo is up-to-date and let me know

**Comment by bernatfortet** [comment]
@paveltaran I had the same problem, then updated using the new NPM package and it works like a charm. Thanks @dparlevliet for being so on top of the game 🙏

**Comment by dparlevliet** [comment]
No problem. Always happy to help my crypto brothers and sisters!

**Comment by paveltaran** [comment]
Oh yeah! 😃
