### ISSUE TITLE
Error: ESOCKETTIMEDOUT while accessing 249 coinpairs through bittrex.getcandles() method .

### ISSUE THREAD

**Issue by droidmanspace** [dparlevliet/node.bittrex.api#141]
```
{ success: false,
  message: 'URL request error',
  error: 
   { Error: ESOCKETTIMEDOUT
       at ClientRequest.<anonymous> (D:\bitt\node_modules\request\request.js:813:19)
       at Object.onceWrapper (events.js:314:30)
       at emitNone (events.js:105:13)
       at ClientRequest.emit (events.js:207:7)
       at TLSSocket.emitTimeout (_http_client.js:722:34)
       at Object.onceWrapper (events.js:314:30)
       at emitNone (events.js:105:13)
       at TLSSocket.emit (events.js:207:7)
       at TLSSocket.Socket._onTimeout (net.js:398:8)
       at ontimeout (timers.js:469:11) code: 'ESOCKETTIMEDOUT', connect: false },
  result: undefined }
```

does every request need some delay?

**Comment by dparlevliet** [comment]
You'd be wise to give it a delay. You either maxed out your internet bandwidth or they blocked your ip as a threat (possibly temporarily).
