### ISSUE TITLE
cannot read property "sigBytes" of undefine

### ISSUE THREAD

**Issue by TomYeoman** [dparlevliet/node.bittrex.api#147]
Hi all,

I'm attempting to use the getbalances call

But recieve this error

```
(node:72932) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'sigBytes' of undefined
    at new init (C:\Users\yoers\Documents\git\trading_server\node_modules\node-bittrex-api\hmac-sha512.js:24:178)
    at Object.HmacSHA512 (C:\Users\yoers\Documents\git\trading_server\node_modules\node-bittrex-api\hmac-sha512.js:12:488)
    at setRequestUriGetParams (C:\Users\yoers\Documents\git\trading_server\node_modules\node-bittrex-api\node.bittrex.api.js:100:38)
    at apiCredentials (C:\Users\yoers\Documents\git\trading_server\node_modules\node-bittrex-api\node.bittrex.api.js:81:12)
    at credentialApiCall (C:\Users\yoers\Documents\git\trading_server\node_modules\node-bittrex-api\node.bittrex.api.js:162:40)
    at Object.getbalances (C:\Users\yoers\Documents\git\trading_server\node_modules\node-bittrex-api\node.bittrex.api.js:454:7)
    at BTRX.getPortfolio (C:\Users\yoers\Documents\git\trading_server\api\model\exchanges\BTRX.js:38:25)
    at Exchange.getPortfolio (C:\Users\yoers\Documents\git\trading_server\api\model\exchanges\exchange.model.js:53:38)
    at exports.getPortfolio (C:\Users\yoers\Documents\git\trading_server\api\controller\bot\exchange.controller.js:28:14)
    at Layer.handle [as handle_request] (C:\Users\yoers\Documents\git\trading_server\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\Users\yoers\Documents\git\trading_server\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\Users\yoers\Documents\git\trading_server\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\Users\yoers\Documents\git\trading_server\node_modules\express\lib\router\layer.js:95:5)
    at C:\Users\yoers\Documents\git\trading_server\node_modules\express\lib\router\index.js:281:22
    at param (C:\Users\yoers\Documents\git\trading_server\node_modules\express\lib\router\index.js:354:14)
    at param (C:\Users\yoers\Documents\git\trading_server\node_modules\express\lib\router\index.js:365:14)
    at Function.process_params (C:\Users\yoers\Documents\git\trading_server\node_modules\express\lib\router\index.js:410:3)
    at next (C:\Users\yoers\Documents\git\trading_server\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\Users\yoers\Documents\git\trading_server\node_modules\express\lib\router\index.js:174:3)
    at router (C:\Users\yoers\Documents\git\trading_server\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\Users\yoers\Documents\git\trading_server\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\Users\yoers\Documents\git\trading_server\node_modules\express\lib\router\index.js:317:13)
(node:72932) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:72932) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I've tried this with incorrect API keys and get the error saying it's not recognised as expected, but when using correct keys I get this.

I'm running Win10, Node v9.4 ( Could this be the problem.. )

**Comment by TomYeoman** [comment]
NVM looks like the key was missing, although I had to debug this manually perhaps we could catch this error ( opts.apisecret was undefined )
