### ISSUE TITLE
Websocket onerror:  Negotiate Unknown

### ISSUE THREAD

**Issue by c0nf1ck** [dparlevliet/node.bittrex.api#99]
A few days ago i'm receiving this error from the websocket listen:

```
[2017-12-20T20:19:32+00:00] Websocket bound
[2017-12-20T20:47:27+00:00] Websocket disconnected
[2017-12-20T20:47:27+00:00] Websocket auto reconnecting
[2017-12-20T20:47:27+00:00] Connection aborted
[2017-12-20T20:47:27+00:00] Websocket bound
[2017-12-20T23:07:48+00:00] Websocket disconnected
[2017-12-20T23:07:48+00:00] Websocket auto reconnecting
[2017-12-20T23:07:48+00:00] Connection aborted
[2017-12-20T23:07:48+00:00] Websocket bound
[2017-12-20T23:44:51+00:00] Websocket disconnected
[2017-12-20T23:44:51+00:00] Websocket auto reconnecting
[2017-12-20T23:44:52+00:00] Websocket onerror:  Negotiate Unknown
[2017-12-20T23:44:53+00:00] Connection aborted
```

and after that it does not try to reconnect again, it was stuck at 'Connection aborted' from few hours now.
My code looks like this:

```
BittrexService.websocketListen = (callback) => {
    bittrex.websockets.client((wsClient) => {
        wsClient.serviceHandlers.connected = (wsConnection) => {
            wsClient.call('CoreHub', 'SubscribeToSummaryDeltas').done((err, result) => {
                if(err) return console.error(err);
    
                if(result === true) {
                    bittrex.websockets.listen((data, client) => {
                        if(data.M === 'updateSummaryState') {
                            _.forEach(data.A, (data) => {
                                callback(data)
                            });
                        }
                    })
                }
            });
        };
    });
}
```

Is something that i'm done wrong?

**Comment by c0nf1ck** [comment]
Anyone ? Up

**Comment by webworker01** [comment]
Not sure if exact same problem, but similar symptoms

`
Error Message:  Negotiate Unknown
Exception:  undefined
Error Data:  503
Websocket bound
Websocket connected
Websocket connectFailed:  Error: Server responded with a non-101 status: 503 Service Unavailable
Response Headers Follow:
date: Tue, 02 Jan 2018 17:22:22 GMT
content-type: text/html
transfer-encoding: chunked
connection: keep-alive
strict-transport-security: max-age=15768000
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-download-options: noopen
server: cloudflare-nginx
cf-ray: 3d6f6668eba25771-IAD
`
`
    at WebSocketClient.failHandshake (/home/program/node_modules/websocket/lib/WebSocketClient.js:326:32)
    at ClientRequest.<anonymous> (/home/program/node_modules/websocket/lib/WebSocketClient.js:265:18)
    at ClientRequest.emit (events.js:159:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:550:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
    at TLSSocket.socketOnData (_http_client.js:439:20)
    at TLSSocket.emit (events.js:159:13)
    at addChunk (_stream_readable.js:265:12)
    at readableAddChunk (_stream_readable.js:252:11)
    at TLSSocket.Readable.push (_stream_readable.js:209:10)
    at TLSWrap.onread (net.js:598:20)
`

**Comment by webworker01** [comment]
Neat changes, thank you Ruff!
